### ISSUE TITLE
Could this be set as a github template?

### ISSUE THREAD

**Issue by dreamy-dev** [bsi-software/bsi-cx-scaffold-design#4]
Is this repository ready to be used as a starting point? If yes, could you please set it up as a template? This way it would be easier to start working with this template. 

Link for clearer definitions on what I mean:
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by marleenbarth** [comment]
Thanks for your comment! We have now set the repository as a GitHub template.
